{% set name = "blark" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/klauer/blark/archive/v{{ version }}.tar.gz
  sha256: 2d8355f559cf56af0270ecd7765ba40dd2913b6280bf597bb91b697ffd260563

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - blark = blark.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytmc
    - lark-parser

test:
  imports:
    - blark
    - blark.tests
  commands:
    - blark --help

about:
  home: https://github.com/klauer/blark
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Beckhoff TwinCAT ST (IEC 61131-3) code parsing in Python using Lark

extra:
  recipe-maintainers:
    - klauer
